using System;

namespace TimiApp.Dapper.ViewModels
{
    public class RevenueReportViewModel
    {
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public DateTime Date { get; set; }
        public decimal Revenue { get; set; } // total amount of income generated by the sale of goods or services related to the company's operations
        public decimal Profit { get; set; } // the bottom line, the amount of income that remains after accounting for all expenses, debts
    }
}
